### ISSUE TITLE
MQTT over QUIC

### ISSUE THREAD

**Issue by sohanpatil1** [wanghaEMQ/pynng-mqtt#1]
Hello,

I am trying to send payload from a publisher to a subscriber implemented in python. How do I set it up such that it works with MQTT over QUIC? The README says it is capable of running with EMQX v5.

I have access to macOS M1 and Ubuntu 22.04 and I am open to working on either depending on what you recommend for this package.

Anything helps,
Thanks

**Comment by wanghaEMQ** [comment]
Yes! It works with EMQX v5.x!
I will update the readme and provide a simple tutorial about installation and its requirement later.

**Comment by wanghaEMQ** [comment]
I have updated the readme. #097ff07ca7a2a9913c96dd17dd56200db80ec7d5

**Comment by wanghaEMQ** [comment]
Note. You may need to modify the MQTT server address in examples/mqttpub.py and examples/mqttsub.py.

**Comment by wanghaEMQ** [comment]
You may need to modify the MQTT server address in examples/mqttpub.py and examples/mqttsub.py. And the msgs sent or received are on QUIC protocol by default.

**Comment by sohanpatil1** [comment]
Thanks for the quick response and offering the instructions for setting it up.
I had two concerns,
- mkdir -f build is one of the commands for installing msquic to the system. Is this correct? What should it be instead?
- When I try pip3 install -e . in the pynng-mqqt directory, I see this error
![GithubIssue](https://user-images.githubusercontent.com/54910728/198413340-21aee86f-43a8-4fd4-b772-9dc53023afe8.png)
- When I tried sudo apt install libssl, Linux was unable to locate package libssl. I added libssl3 instead. Please let me know if this needs to be corrected

How do I fix this? I searched online but couldn't figure it out.
Thanks,
Sohan

**Comment by wanghaEMQ** [comment]
> mkdir -f build is one of the commands for installing msquic to the system. Is this correct? What should it be instead?

I am sorry for my mistake. The command should be ```mkdir -p build```.

> When I try pip3 install -e . in the pynng-mqqt directory, I see this error

Maybe a version mismatch happened on cffi. cffi-1.15.1 is requires. But only cffi-1.15.0 be found on your system.

> When I tried sudo apt install libssl, Linux was unable to locate package libssl. I added libssl3 instead. Please let me know if this needs to be corrected

Is there are libssl-dev package found?

**Comment by sohanpatil1** [comment]
I checked my cffi installation version, it is 1.15.1. I checked it with 'pip show cffi'.
Yes there is a libssl-dev package and I have added it. However, still getting the same error. 
![image](https://user-images.githubusercontent.com/54910728/198527067-af1b61fc-5e99-433d-8276-4a12ffd845c3.png)

I am using python 3.10.6

**Comment by wanghaEMQ** [comment]
Try to downgrade cffi to 1.15.0

> sudo pip3 install cffi==1.15.0

Better if you remove it first

**Comment by sohanpatil1** [comment]
I downgraded cffi to 1.15.0. I am following this [website](https://stackoverflow.com/questions/68592184/error-version-of-cffi-python-package-mismatch) for assistance.
I ran these commands to make it work. I used sudo when I realized there were permission issues. However I am still stuck.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/54910728/199131207-6b432f4b-032d-45cb-9272-5494ca623a42.png">

I have printed my console below:

![image](https://user-images.githubusercontent.com/54910728/199134398-1a35068d-849c-4a3a-b50e-8b197ceca204.png)
![image](https://user-images.githubusercontent.com/54910728/199134442-1d7bb7dd-ab6a-4a75-b4f3-e3ae75f0c28b.png)

**Comment by wanghaEMQ** [comment]
Your local installation (/home/ubuntu/.local/lib/python3.10/...) failed.  When you try to run the mqttsub.py. 
 It finds the pynng in your local installation first. But not your global success one (/usr/local/lib/python3.10/...).

Perhaps you could run with sudo. Or remove the local failed one. :)

**Comment by sohanpatil1** [comment]
I believe I have safely removed the local one. When I run the 2 python files (mqttsub.py and mqttpub.py), they both stop at async-await on line 22/24 and no connection message is sent. I have reviewed the files to see where the issue maybe, but no luck. Is it because of the mqtt server address? 
Any help would be greatly appreciated!

EDIT : I searched on EMQX's website and I noticed "mqtt-quic:127.0.0.1:14567" for QUIC and looks like it is correct. What's causing the issue?

**Comment by wanghaEMQ** [comment]
Did you forget to start your emqx broker? or the option in the configuration which enables QUIC?
You could check if there are any processes listening 14567

```
sudo lsof -i:14567
```

**Comment by sohanpatil1** [comment]
Yes you were right. I did not have EMQX installed on the Ubuntu22.04 instance.
I am now working on Ubuntu 20.04. All my progress so far was for the 22.04 installation. My question now, is for the new installation on Ubuntu 20.04

On running 'pip install -e .' I get a response that says pynng is successfully installed. However I don't see it in pip list or pip list --user.
This is my pip list
![image](https://user-images.githubusercontent.com/54910728/199865813-16b5df58-c035-49c1-ae10-4924b7b7bc50.png)

**Comment by wanghaEMQ** [comment]
Plz also show your```sudo pip list```

**Comment by sohanpatil1** [comment]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/54910728/199876104-bba4c76d-1792-4047-bbd1-f01a16628723.png">

**Comment by wanghaEMQ** [comment]
Do you want to import pynng to your project?

```pip install -e .``` will install pynng in an editable mode (something like debug mode).
If you want to install pynng to your ubuntu20.04 instance and import it to your project.
```pip install .```  should works. Then you can find it in pip list.

**Comment by sohanpatil1** [comment]
Thanks! It worked, and I am able to use it as expected for Ubuntu20.04!
