### ISSUE TITLE
The example "mqtt_quic_pub.py" won't quit and the socket won't be closed.

### ISSUE THREAD

**Issue by iotexplorer-666** [wanghaEMQ/pynng-mqtt#4]
I'm trying MQTT over QUIC with `examples\mqtt_quic_pub.py` in an ubuntu 20.04 server. EMQX 5.0.15 is the MQTT broker that I'm using.
Everything works fine. I published a message with `examples\mqtt_quic_pub.py` and the subscriber could receive the message. But I wonder why the python process `examples\mqtt_quic_pub.py` won't quit after the message is already received by subscribers. Even a "ctrl + c" doesn't help. I have to open another terminal and kill the python process manually which really confuses me.

---

I tried to print some logs to analyse what happens and how to fix it. Please have a look at what I added.

`examples\mqtt_quic_pub.py` -> Please pay attention to the print command `print("breakpoint *")` I added.
```
"""
MQTT is used for synchronous communications where each question is responded with a single answer,
for example remote procedure calls (RPCs).
Like Pipeline, it also can perform load-balancing.
This is the only reliable messaging pattern in the suite, as it automatically will retry if a request is not matched with a response.

"""
import sys
import pynng
import curio

helper = "Usage:\n\tmqttpub.py <topic> <qos> <payload>"

address = "mqtt-quic://127.0.0.1:14567"

async def main():
    with pynng.Mqtt_quic(address) as mqtt:
      print(f"Make a connect msg")
      connmsg = pynng.Mqttmsg()
      connmsg.set_packet_type(1) # 0x01 Connect
      connmsg.set_connect_proto_version(4) # MqttV311
      connmsg.set_connect_username("alvin")
      connmsg.set_connect_password("alvin123")
      await mqtt.asend_msg(connmsg)
      print(f"Connect packet sent.")
      pubmsg = pynng.Mqttmsg()
      pubmsg.set_packet_type(3) # 0x03 Publish
      pubmsg.set_publish_topic(sys.argv[1])
      pubmsg.set_publish_qos(int(sys.argv[2]))
      pld = sys.argv[3]
      pubmsg.set_publish_payload(pld, len(pld))
      await mqtt.asend_msg(pubmsg)
      print(f"Publish packet sent.")
      # mqtt.close()
      print("breakpoint 0")
      mqtt.socket = None
      mqtt._socket = None
    print("breakpoint 1")

if __name__ == "__main__":
  if len(sys.argv) != 4:
    print(helper)
    exit(0)
  try:
    curio.run(main)
  except KeyboardInterrupt:
    # that's the way the program *should* end
    exit(0)

  print("breakpoint 2")
```

`pynng/nng.py  Socket.close()` Please pay attention to the print command `print('close-*')` I added

```
    def close(self):
        """Close the socket, freeing all system resources."""
        # if a TypeError occurs (e.g. a bad keyword to __init__) we don't have
        # the attribute _socket yet.  This prevents spewing extra exceptions
        print('close-1')
        if hasattr(self, '_socket'):
            print('close-2')
            lib.nng_close(self.socket)
            print('close-3')
            # cleanup the list of listeners/dialers.  A program would be likely to
            # segfault if a user accessed the listeners or dialers after this
            # point.
            self._listeners = {}
            self._dialers = {}
```

After modifying the above files, I ran the quic example again. The output is as follows:
```
root@quic-server:/usr/local/src/mqtt-quic-python# python3 mqtt_quic_pub.py /dev/dev_id/1234 1 test_pub_message
Make a connect msg
Connect packet sent.
Publish packet sent.
breakpoint 0
close-1
close-2
```

As you can see, it's stuck when it tries to close the socket by using nng lib. As I said above, "ctrl + c" doesn't help. To locate this issue, I also tried [the MQTT SDK in C language released by EMQ NanoMQ team ](https://github.com/nanomq/NanoSDK/) and the version I used is 0.8.0, it works well and can quit after I removed a [dead loop](https://github.com/emqx/NanoSDK/blob/main/demo/quic/client.c#L232) which only works for subscription I think.

---

It would be appreciated if you could give me some advice on how to quit it safely and tell me what's going on here.

**Comment by wanghaEMQ** [comment]
Hi. @iotexplorer-666 

The error that the publish/subscribe client won't quit was caused by the aio backend `curio`. And now `curio` has been [replaced](https://github.com/wanghaEMQ/pynng-mqtt/commit/a7fa5c4fc458dd5001f4f7b97964398c6910fd5b) with `asyncio` library and the publish/subscribe client can quit safely.

To use ctrl-c to stop the client. Please add the signal handler to asyncio.

**Comment by iotexplorer-666** [comment]
@wanghaEMQ  Thank you for your reply. I tried the latest example code for quic client and got the following error.
```
root@emqx-broker:/etc/emqx/pynng-mqtt/examples/new-version# python mqtt-quic-pub.py test 1 test2
Make a connect msg
Connect packet sent.
Publish packet sent. 5
Publish packet sent. 5
close-1
close-2
^C^C^C^Cquic_mqtt_stream_finit.
```

As you can see, it still couldn't quit safely even I executed ctrl-c. Did I miss something? I noticed you did change something else but I'm not sure if it matters. I will build pynng with latest code and try it again.

**Comment by wanghaEMQ** [comment]
To stop the client with ctrl-c. Please add the signal handler to asyncio. And make asyncio to remove all the tasks when getting a signal SIGINT or SIGABRT.

**Comment by iotexplorer-666** [comment]
@wanghaEMQ  Thank you very much for your kind support. I rebuilt pynng and it's fixed now.
