### ISSUE TITLE
Instructions to build for ARM64

### ISSUE THREAD

**Issue by leoberteck** [wanghaEMQ/pynng-mqtt#8]
I am trying to test this client on an actual device running on arm64 processor. Any additional instructions to build the project for such target?

**Comment by wanghaEMQ** [comment]
Sorry. This project is just for demo. Don't put it to production.

If you wanna use MQTT Over QUIC functionality. NanoSDK is a better choose. https://github.com/emqx/nanosdk
Building NanoSDK directly on a arm64 processor or cross compiling are supported.

**Comment by leoberteck** [comment]
Thanks for the feedback!
